### ISSUE TITLE
SOUND sound sound

### ISSUE THREAD

**Issue by Beatalchemie** [Befaco/Oneiroi#15]
HI
It's like this: if you turn up all the effects (delay, ambience) then everything gets quieter. It would be good to turn the level up a bit at the output. A saturator or compressor or limiter would be really great. The module is always quieter than other modules in the rack.
THANKS FOR YOUR GREAT WORK!!!!

**Comment by fuzboxz** [comment]
Agreed, some sort of gain equalization would be awesome!

**Comment by hirnlego** [comment]
@Beatalchemie @fuzboxz could you try with the latest beta 8?  Thanks!

**Comment by fuzboxz** [comment]
@hirnlego Just checked it. Thanks, it works perfectly! 🙏
