### ISSUE TITLE
Saving command do not work well on  attenuverter mode

### ISSUE THREAD

**Issue by Diegoterrores** [Befaco/Oneiroi#2]
Found when the module is on attenuverter mode has issues while saving the CV Mapping.

Mapping does not get saved by the Save command or cv stops working at the next startup.

**Comment by hirnlego** [comment]
@Diegoterrores I think this should be fixed in the latest release (v1.1-beta), please check:
https://github.com/Befaco/Oneiroi/releases/tag/v1.1-beta
