### ISSUE TITLE
Still have issue with 1v/oct control of the oscillators

### ISSUE THREAD

**Issue by blave** [Befaco/Oneiroi#29]
I am still experiencing this: 

"I have the keyboard's CV1 1v/oct output patched to the Pitch knob. When I do that, the pitch emitted is at a very low, almost sub-sonic frequency, and neither the keyboard or the pitch knob changes the pitch. If I unplug the pitch CV, the pitch knob behaves normally."

_Originally posted by @blave in https://github.com/Befaco/Oneiroi/issues/28#issuecomment-2526370935_

**Comment by hirnlego** [comment]
@blave have you tried with the V/OCT CV mapping? 

- Press Shift and “CV AMT” buttons to get to CV mapping mode. CV AMT button will turn green.
- Turn Pitch knob all the way clockwise (100%).
- Exit CV mapping by pressing shift again.
- Save settings by holding the “Mod Amt” (same button but without Shift this time) button for two seconds.
